import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { Container } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme';
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import ModeSwitch from '@/components/mode-switch';
import MainHeader from '@/components/main-header/main-header';

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Tavern Ledger | A Task Management App",
  description: "Generated by create next app"
};

// <body className={`${geistSans.variable} ${geistMono.variable}`}>

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
                <MainHeader />
                <Container>
                  {children}
                </Container>
              <ModeSwitch />
            </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
    </html>
  );
}
