import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { Container } from '@mui/material';
import Grid from '@mui/material/Grid2';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/theme';
import ModeSwitch from '@/components/mode-switch';
import MainHeader from '@/components/main-header/main-header';
import QuestListLayout from '@/components/quest-list-layout';


export const metadata: Metadata = {
  title: "Tavern Ledger | A Task Management App",
  description: "Generated by create next app"
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
        <body>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <CssBaseline />
                <MainHeader />
                <Container>
                  <QuestListLayout>{children}</QuestListLayout>
                </Container>
              <ModeSwitch />
            </ThemeProvider>
        </AppRouterCacheProvider>
        </body>
    </html>
  );
}
